In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 4, 7])
a

array([1, 2, 3, 4, 7])

In [12]:
a[4] = 12

In [13]:
a

array([ 1,  2,  3,  4, 12])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [33]:
n[2, 1] = 23

In [43]:
n

array([[4, 7, 3],
       [4, 7, 3],
       [4, 7, 3]])

In [44]:
n[:]

array([[4, 7, 3],
       [4, 7, 3],
       [4, 7, 3]])

In [50]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [49]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [53]:
np.random.seed(2)
np.random.randint(low=23, high=29, size=(5, 2))

array([[23, 28],
       [23, 26],
       [25, 26],
       [23, 25],
       [24, 26]])