In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v

array([ 2,  0,  0, 12])

In [10]:
u.shape[0]

4

In [13]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return float(result)

In [14]:
vector_vector_mult(u, v)

14.0

In [17]:
u.dot(v)

np.int64(14)

In [18]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [24]:
v = np.array([1, 0.5, 2, 1])

In [39]:
U[0]

array([2, 4, 5, 6])

In [30]:
U[0, 3]

np.int64(6)

In [26]:
v.shape[0]

4

In [40]:
def mat_vec_mult(U, v):
    assert U.shape[1] == v.shape[0]

    rows = U.shape[0]
    result = np.zeros(rows)

    for i in range(rows):
        result[i] = vector_vector_mult(U[i], v)

    return result

In [41]:
mat_vec_mult(U, v)

array([20. ,  6. ,  8.5])

In [42]:
U.dot(v)

array([20. ,  6. ,  8.5])